services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: ubuntu-bind
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - rede-litoral
    volumes:
      - ./dns/db.minhoto.com:/etc/bind/db.minhoto.com
      - ./dns/named.conf.local:/etc/bind/named.conf.local

networks:
  rede-litoral:
    driver: bridge
