services:
  dns:
    build:
      context: ./provedor/dns
      dockerfile: Dockerfile
    image: ubuntu-bind
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - rede-litoral
    volumes:
      - ./provedor/dns/db.pescadores.com:/etc/bind/db.pescadores.com
      - ./provedor/dns/named.conf.local:/etc/bind/named.conf.local
