services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: ubuntu-bind
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - rede-litoral
    volumes:
      - ./dns/db.rosado.com:/etc/bind/db.rosado.com
      - ./dns/db.minhoto.com:/etc/bind/db.minhoto.com
      - ./dns/db.camapum.com:/etc/bind/db.camapum.com
      - ./dns/named.conf.local:/etc/bind/named.conf.local
    restart: always

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: nginx-proxy
    container_name: proxy_provedor
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rede-litoral
    volumes:
    - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    - ./proxy/ssl-cert:/etc/nginx/ssl-cert 
    depends_on:
      - dns
    restart: always
    
  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    container_name: mail
    networks:
      - rede-litoral
    ports:
      - "25:25"    # Porta do SMTP
      - "110:110"  # Porta do POP3
      - "143:143"  # Porta do IMAP
      - "993:993"  # Porta do IMAPS (SSL)
      - "995:995"  # Porta do POP3S (SSL)
    volumes:
      - ./mail/maildata:/maildata
    environment:
      - MAIL_DOMAIN=rosado.com
    restart: always

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    networks:
      - rede-litoral

    volumes:
      - ./webmail/config.inc.php:/var/www/html/config/config.inc.php
    depends_on:
      - dns
      - mail
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=imaps://mail.rosado.com
      - ROUNDCUBEMAIL_SMTP_SERVER=smtp://mail.rosado.com
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_DB_DSN=sqlite:////var/www/html/roundcubemail.sqlite
    restart: always

  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    container_name: ssh_provedor
    ports:
      - "22:22"
    networks:
      - rede-litoral
    restart: always

networks:
  rede-litoral:
    driver: bridge
