services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy_cliente1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rede-litoral
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl-cert:/etc/nginx/ssl
    depends_on:
      - wellton
      - gabriel
    restart: always

  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    container_name: ssh_cliente1
    ports:
      - "2222:22"
    networks:
      - rede-litoral
    restart: always

  wellton:
    image: wordpress:latest
    container_name: wellton
    environment:
      WORDPRESS_DB_HOST: db_wellton:3306
      WORDPRESS_DB_NAME: wordpress_wellton
      WORDPRESS_DB_USER: user_wellton
      WORDPRESS_DB_PASSWORD: redes
    volumes:
      - wordpress_data_wellton:/var/www/html
    networks:
      - rede-litoral
    depends_on:
      - db_wellton
    ports:
      - "8081:80"
    restart: always

  gabriel:
    image: wordpress:latest
    container_name: gabriel
    environment:
      WORDPRESS_DB_HOST: db_gabriel:3306
      WORDPRESS_DB_NAME: wordpress_gabriel
      WORDPRESS_DB_USER: user_gabriel
      WORDPRESS_DB_PASSWORD: redes
    volumes:
      - wordpress_data_gabriel:/var/www/html
    networks:
      - rede-litoral
    depends_on:
      - db_gabriel
    ports:
      - "8082:80"
    restart: always

  db_wellton:
    image: mysql:5.7
    container_name: mysql_wellton
    environment:
      MYSQL_ROOT_PASSWORD: redes
      MYSQL_DATABASE: wordpress_wellton
      MYSQL_USER: user_wellton
      MYSQL_PASSWORD: redes
    volumes:
      - db_data_wellton:/var/lib/mysql
    networks:
      - rede-litoral
    restart: always

  db_gabriel:
    image: mysql:5.7
    container_name: mysql_gabriel
    environment:
      MYSQL_ROOT_PASSWORD: redes
      MYSQL_DATABASE: wordpress_gabriel
      MYSQL_USER: user_gabriel
      MYSQL_PASSWORD: redes
    volumes:
      - db_data_gabriel:/var/lib/mysql
    networks:
      - rede-litoral
    restart: always

networks:
  rede-litoral:
    driver: bridge

volumes:
  wordpress_data_wellton:
  wordpress_data_gabriel:
  db_data_wellton:
  db_data_gabriel:
