services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - rede-litoral
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wellton
      - gabriel

  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    container_name: ssh
    ports:
      - "2222:22"
    networks:
      - rede-litoral

  wellton:
    build:
      context: ./wellton
      dockerfile: Dockerfile
    container_name: wordpress-wellton
    environment:
      WORDPRESS_DB_HOST: db-wellton:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: redes
    volumes:
      - wordpress_data_wellton:/var/www/html
    networks:
      - rede-litoral
    depends_on:
      - db-wellton
    ports:
      - "8081:80"

  db-wellton:
    image: mysql:5.7
    container_name: mysql-wellton
    environment:
      MYSQL_ROOT_PASSWORD: redes
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: redes
    volumes:
      - db_data_wellton:/var/lib/mysql
    networks:
      - rede-litoral

  gabriel:
    build:
      context: ./gabriel
      dockerfile: Dockerfile
    container_name: wordpress-gabriel
    environment:
      WORDPRESS_DB_HOST: db-gabriel:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: redes
    volumes:
      - wordpress_data_gabriel:/var/www/html
    networks:
      - rede-litoral
    depends_on:
      - db-gabriel
    ports:
      - "8082:80"

  db-gabriel:
    image: mysql:5.7
    container_name: mysql-gabriel
    environment:
      MYSQL_ROOT_PASSWORD: redes
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: redes
    volumes:
      - db_data_gabriel:/var/lib/mysql
    networks:
      - rede-litoral

networks:
  rede-litoral:
    driver: bridge

volumes:
  wordpress_data_wellton:
  db_data_wellton:
  wordpress_data_gabriel:
  db_data_gabriel:
